# Generated by Django 3.2.9 on 2022-04-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='images/')),
                ('city', models.CharField(default=None, max_length=40)),
                ('state', models.CharField(default=None, max_length=40)),
                ('pincode', models.IntegerField(default=None)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
