# Generated by Django 4.0.3 on 2022-04-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_ourpatient_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourpatient',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
